version: '3.8'

services:

  app:
    build:
      context: node 
    container_name: app
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules    
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s sh -c "npm install && node index.js" # executa o dockerize ate subir o banco e apos executa o comando para subir o node
#    command: ["node", "index.js"]
    networks:
      - node-network
    tty: true
    depends_on: # inicia o container depois do inidcado, mas nao espera as app ficar no ar
      - db


  db:
    image: mysql:8.0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./init_db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network
    ports:
      - "3306:3306"     

  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    image: diogosantinon/nginx:prod
    container_name: nginx
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on: # inicia o container depois do inidcado, mas nao espera as app ficar no ar
      - db
      - app      

networks:
  node-network:
    driver: bridge